version: "3.3"

services:
    test_db:
        image: mysql:8.0.23
        platform: linux/amd64
        container_name: test_db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            
    omios:
        build:
            dockerfile: Dockerfile.dev
        container_name: omios_dev
        ports:
            - "8000:8000"
        env_file: 
            - ./.env.dev
        environment:
            TEST_DB_USER: root
            TEST_DB_PASSWORD: password
            TEST_DB_HOST: test_db
            TEST_DB_PORT: 3306
        depends_on:
            - test_db

        command: >
            sh -c "python ./api/manage.py runserver 0.0.0.0:8000"