version: "3.3"

services: 
    omios:
        build:
            dockerfile: Dockerfile.prod
        container_name: omios_webserver
        expose:
            - "8000"
        env_file: 
            - ./.env.prod
        command: >
            sh -c "cd api && gunicorn"

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80/tcp"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - omios