version: "3.3"

services:
    omios:
        build:
            dockerfile: Dockerfile.dev
        container_name: omios_dev
        ports:
            - "8000:8000"
        env_file: 
            - ./.env.dev
        command: >
            sh -c "python ./api/manage.py runserver 0.0.0.0:8000"